### ISSUE TITLE
代码运行不起来

### ISSUE THREAD

**Issue by lispwu** [Aresyi/HowTomcatWorks#1]
Error:(77, 34) java: 程序包org.apache.commons.modeler不存在
Error:(70, 35) java: 程序包org.apache.commons.digester不存在
Error:(72, 30) java: 程序包org.apache.tomcat.util不存在

**Comment by Aresyi** [comment]
所依赖的jar都在lib下面

**Comment by fengyouliang** [comment]
使用idea的话，需要将lib folder 右键 Add as Library 
Add to module 中选择 how-tomcat-works-util

**Comment by whitehatXiao** [comment]
请问一下各位使用的是JDK几呢？
